This is makeindex, version 2.15 [MiKTeX 2.9.6880 64-bit] (kpathsea + Thai support).
Scanning style file ./bac.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file bac.acn....done (103 entries accepted, 0 rejected).
Sorting entries....done (764 comparisons).
Generating output file bac.acr....done (65 lines written, 0 warnings).
Output written in bac.acr.
Transcript written in bac.alg.
