This is makeindex, version 2.15 [MiKTeX 2.9.6880 64-bit] (kpathsea + Thai support).
Scanning style file ./example_.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file example_.acn....done (102 entries accepted, 0 rejected).
Sorting entries....done (762 comparisons).
Generating output file example_.acr....done (65 lines written, 0 warnings).
Output written in example_.acr.
Transcript written in example_.alg.
